"""Golden output generator for ByteTracker C++ port.

5 フレーム分の固定入力で track_id 列を生成し、tests/golden_byte_tracker.txt
に保存する。C++ port が同じ入力で同じ track_id 列を返すことを検証する。
"""
from __future__ import annotations

import sys
from pathlib import Path

# shuttlescope/ を sys.path に追加 (scripts/gen_golden.py の 4 つ上)
# scripts -> person_tracker_native -> cv -> backend -> shuttlescope
SHUTTLESCOPE_DIR = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(SHUTTLESCOPE_DIR))

from backend.cv.byte_tracker import ByteTracker, Detection


def main() -> None:
    tracker = ByteTracker(
        track_high_thresh=0.8,
        track_low_thresh=0.5,
        new_track_thresh=0.8,
        track_buffer=120,
        match_thresh_high=0.8,
        match_thresh_low=0.5,
        match_thresh_unconfirmed=0.7,
    )
    # 2 人の人物が画面内を歩く + 1 人途中で消える scenario
    # 各フレーム: list of (x1, y1, x2, y2, score)
    frames: list[list[tuple[float, float, float, float, float]]] = [
        # frame 0
        [(100.0, 200.0, 200.0, 400.0, 0.9), (300.0, 200.0, 400.0, 400.0, 0.85)],
        # frame 1: 両方 5 px 右に
        [(105.0, 200.0, 205.0, 400.0, 0.9), (305.0, 200.0, 405.0, 400.0, 0.85)],
        # frame 2: 両方 さらに右
        [(110.0, 200.0, 210.0, 400.0, 0.9), (310.0, 200.0, 410.0, 400.0, 0.85)],
        # frame 3: 1 人消える
        [(115.0, 200.0, 215.0, 400.0, 0.9)],
        # frame 4: 復活
        [(120.0, 200.0, 220.0, 400.0, 0.9), (320.0, 200.0, 420.0, 400.0, 0.85)],
    ]

    out_lines: list[str] = []
    out_lines.append("# golden_byte_tracker.txt")
    out_lines.append("# format: frame_id track_id x1 y1 x2 y2 score is_activated")
    out_lines.append("# generated by scripts/gen_golden.py from backend/cv/byte_tracker.py")
    for fid, dets_raw in enumerate(frames):
        dets = [Detection(bbox=(d[0], d[1], d[2], d[3]), score=d[4]) for d in dets_raw]
        out = tracker.update(dets, frame_id=fid)
        for t in out:
            x1, y1, x2, y2 = t.xyxy
            out_lines.append(
                f"{fid} {t.track_id} {x1:.6f} {y1:.6f} {x2:.6f} {y2:.6f} {t.score:.6f} {int(t.is_activated)}"
            )

    golden_path = Path(__file__).resolve().parent.parent / "tests" / "golden_byte_tracker.txt"
    golden_path.parent.mkdir(parents=True, exist_ok=True)
    golden_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    print(f"wrote: {golden_path}")
    print("\n".join(out_lines))


if __name__ == "__main__":
    main()
