"""Material Symbols Outlined のサブセットフォントを生成する。

実行: cd shuttlescope && python scripts/subset_material_symbols.py

入力:  node_modules/material-symbols/material-symbols-outlined.woff2 (~3.9 MB)
出力:  src/assets/fonts/material-symbols-subset.woff2 (~30-100 KB)

サブセット対象 icon は MIcon name="..." を src/ から自動抽出する。

material-symbols は ligature 方式 (= 文字列 "play_arrow" を font 内で 1 glyph に
合成) なので、subset 時に --text に icon 名を含めれば必要 glyph + ligature ルール
だけが残る。

使用 icon を追加したら再実行 → src/styles/material-symbols-subset.css を ts file
で import している経路を経由してビルドに含まれる。
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parent.parent  # shuttlescope/
SRC = ROOT / "src"
FONT_SRC = ROOT / "node_modules" / "material-symbols" / "material-symbols-outlined.woff2"
ASSETS = ROOT / "src" / "assets" / "fonts"
FONT_OUT = ASSETS / "material-symbols-subset.woff2"
CSS_OUT = ROOT / "src" / "styles" / "material-symbols-subset.css"


def collect_icon_names() -> list[str]:
    """src/ 配下から MIcon name="..." と name={...} の両方を grep して unique 一覧を返す。

    static: MIcon name="play_arrow"
    dynamic: MIcon name={open ? 'expand_more' : 'expand_less'}
           → 'expand_more' / 'expand_less' 両方拾う
    """
    # static literal: MIcon name="foo" / name='foo'
    static_pat = re.compile(r'MIcon\s+name=["\']([a-z_][a-z_0-9]*)["\']')
    # dynamic expr inside braces: 名前候補は 'foo' / "foo" 形のリテラルだけを抽出
    dynamic_pat = re.compile(r'MIcon[^>]{0,200}name=\{([^}]+)\}', re.DOTALL)
    literal_in_expr = re.compile(r"['\"]([a-z_][a-z_0-9]*)['\"]")
    names: set[str] = set()
    for p in list(SRC.rglob("*.tsx")) + list(SRC.rglob("*.ts")):
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        names.update(static_pat.findall(text))
        for expr in dynamic_pat.findall(text):
            # 三項や OR の中の 'foo' 'bar' 等を全部拾う
            for lit in literal_in_expr.findall(expr):
                # Material Symbols の典型 icon 名 (snake_case 英小文字数字のみ)
                if 2 <= len(lit) <= 40 and lit.replace("_", "").isalnum():
                    names.add(lit)
    return sorted(names)


def main() -> int:
    if not FONT_SRC.exists():
        print(f"ERROR: source font not found: {FONT_SRC}")
        print("  → cd shuttlescope && npm install (material-symbols 入手)")
        return 2

    names = collect_icon_names()
    if not names:
        print("WARN: no MIcon name found in src/ — abort")
        return 2

    ASSETS.mkdir(parents=True, exist_ok=True)
    # ligature 結合に必要な文字 (alphabet + _) を text 引数で渡す。
    # material-symbols は icon 名そのものを font 入力テキストに使う ligature 方式。
    text = "\n".join(names)

    # Step 1: variable font の axis を固定して static font 化
    # (= variable axes / variation table 全 drop で ~3MB の dead weight 削減)
    print("[subset] step 1: instancing (variable → static)")
    src_font = TTFont(str(FONT_SRC))
    static_font = instantiateVariableFont(
        src_font,
        axisLimits={"FILL": 0, "wght": 400, "GRAD": 0, "opsz": 24},
    )
    static_path = ASSETS / "_static.ttf"
    static_font.save(str(static_path))
    static_size = static_path.stat().st_size
    print(f"[subset]   static: {static_size/1024:.1f} KB")

    # Step 2: static font に対して subset (使う icon の glyph + ligature だけ残す)
    print("[subset] step 2: pyftsubset (keep used icons only)")
    args = [
        str(static_path),
        f"--text={text}",
        "--layout-features=liga,calt,clig,dlig,rlig",
        "--no-hinting",
        "--ignore-missing-unicodes",
        "--no-glyph-names",
        f"--output-file={FONT_OUT}",
        "--flavor=woff2",
        "--with-zopfli",
    ]
    print(f"[subset] icons={len(names)} → {FONT_OUT.name}")
    print(f"[subset] icons: {names}")
    subset.main(args)

    # 中間 static ttf を削除
    static_path.unlink(missing_ok=True)

    src_size = FONT_SRC.stat().st_size
    out_size = FONT_OUT.stat().st_size
    pct = 100 * out_size / src_size
    print(f"[subset] {src_size/1024:.1f} KB → {out_size/1024:.1f} KB ({pct:.1f}%)")

    # CSS 出力 (相対パスで font 参照 / Vite asset hash で content-hash 付与)
    css = f"""/* Auto-generated by scripts/subset_material_symbols.py.
   元の material-symbols/outlined.css ({src_size/1024:.0f} KB) を {out_size/1024:.0f} KB に圧縮。
   icon 追加時は scripts/subset_material_symbols.py を再実行する。
*/
@font-face {{
  font-family: "Material Symbols Outlined";
  font-style: normal;
  font-weight: 100 700;
  font-display: block;
  src: url("../assets/fonts/material-symbols-subset.woff2") format("woff2");
}}
.material-symbols-outlined {{
  font-family: "Material Symbols Outlined";
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
  font-feature-settings: "liga";
  font-variation-settings: "FILL" 0, "wght" 400, "GRAD" 0, "opsz" 24;
}}
"""
    CSS_OUT.write_text(css, encoding="utf-8")
    print(f"[subset] wrote {CSS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
