"""analysis_config.py — 解析系共通設定・閾値"""


class AnalysisConfig:
    LONG_RALLY_THRESHOLD = 10
    SHORT_RALLY_MAX = 4
    STREAK_MIN_LENGTH = 3
    PRESSURE_SCORE_THRESHOLD = 17
    ATTACKER_MAX_RALLY_LEN = 6
    ATTACKER_MIN_SMASH_RATE = 0.30
    DEFENDER_MIN_RALLY_LEN = 10
    BASELINE_WIN_RATE = 0.5
    RECOMMENDATION_NORM_N = 300.0
    RECOMMENDATION_MIN_SAMPLES = 5
    GROWTH_TREND_DELTA = 0.03
    MIN_RALLIES_STABLE = 50
    MIN_RALLIES_ADVANCED = 150
    MIN_RALLIES_RESEARCH = 300
    MIN_SEQUENCES_PATTERN = 5
    MIN_OBS_SPATIAL = 5
    SCORE_MOMENTUM_SWING = 3
    NET_FRONT_Y_THRESHOLD = 0.4
    BALANCE_RATIO_MIN = 0.35
    SHORT_RALLY_LABEL_MAX = 4
    MEDIUM_RALLY_LABEL_MAX = 8
