"""モデルファイル整合性検証 (Round 258 #8)

backend/models/ 配下の ML モデルファイル (.onnx / .pt / .pth) を
SHA-256 で hash し、`backend/models/SHA256SUMS` に記録された期待値と比較する。

目的:
  1. tamper detection (バックドア入りモデルへの差し替え検知)
  2. サプライチェーン整合性 (CDN MITM / cache 汚染検知)
  3. 監査追跡 (git diff で「いつどのモデルが入れ替わったか」が見える)
  4. 再現性 (報告書に出した結果のモデル hash を後から検証可能)

運用:
  - モデルを正当に更新した直後に scripts/regenerate_model_manifest.py を実行
    して SHA256SUMS を更新し、commit する。
  - backend 起動時に verify_models() が呼ばれる。MISMATCH → CRITICAL ログ
    + (本番なら exit 1)、UNEXPECTED → WARNING (新規モデル: 手動更新待ち)。
  - 検証対象拡張子は MODEL_EXTENSIONS。trt_cache/ 等の自動生成キャッシュは除外。
"""
from __future__ import annotations

import hashlib
import logging
import os
from pathlib import Path
from typing import Optional

logger = logging.getLogger("shuttlescope.model_integrity")

# 検証対象拡張子
MODEL_EXTENSIONS = {".onnx", ".pt", ".pth", ".safetensors"}

# trt_cache/ など実行時に再生成される一時物は除外
EXCLUDE_DIRS = {"trt_cache", "__pycache__"}

DEFAULT_MODELS_DIR = Path(__file__).resolve().parent.parent / "models"
DEFAULT_MANIFEST_PATH = DEFAULT_MODELS_DIR / "SHA256SUMS"


def _sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _iter_model_files(models_dir: Path):
    if not models_dir.exists():
        return
    for root, dirs, files in os.walk(models_dir):
        # in-place dirs filter で EXCLUDE_DIRS を walk から除外
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        root_path = Path(root)
        for fn in files:
            ext = Path(fn).suffix.lower()
            if ext in MODEL_EXTENSIONS:
                yield root_path / fn


def compute_manifest(models_dir: Optional[Path] = None) -> dict[str, str]:
    """models_dir 配下のモデルファイル → {relative_path: sha256_hex}.

    relative_path は POSIX 形式 (Win/Linux で同じ manifest を使えるように)。
    """
    if models_dir is None:
        models_dir = DEFAULT_MODELS_DIR
    out: dict[str, str] = {}
    for p in _iter_model_files(models_dir):
        rel = p.relative_to(models_dir).as_posix()
        out[rel] = _sha256_file(p)
    return out


def parse_manifest(path: Path) -> dict[str, str]:
    """SHA256SUMS テキストを {relative_path: sha256_hex} に変換.

    フォーマットは標準 `sha256sum` 互換 (`<hex>  <path>` の 2-space 区切り)。
    `# ` で始まる行はコメント、空行は無視。
    """
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # sha256sum format: "<hex>  <path>" (2 spaces) or "<hex> *<path>" (binary mode)
        # tolerate either single or double space
        parts = line.split(None, 1)
        if len(parts) != 2:
            continue
        hex_part, name_part = parts[0].lower(), parts[1].lstrip("*").strip()
        if len(hex_part) != 64 or any(c not in "0123456789abcdef" for c in hex_part):
            continue
        # POSIX 化 (Windows パスで保存されていても read 時に / に統一)
        out[name_part.replace("\\", "/")] = hex_part
    return out


def render_manifest(entries: dict[str, str]) -> str:
    """{path: hex} を sha256sum 互換テキストに整形 (deterministic order)."""
    lines = [
        "# ShuttleScope model file SHA-256 manifest",
        "# Generated by backend/utils/model_integrity.py",
        "# Update via: python -m backend.scripts.regenerate_model_manifest",
        "# Round 258 #8: tamper detection / supply-chain integrity",
        "",
    ]
    for rel in sorted(entries):
        lines.append(f"{entries[rel]}  {rel}")
    lines.append("")  # trailing newline
    return "\n".join(lines)


class ModelIntegrityResult:
    def __init__(self):
        self.matched: list[str] = []
        self.mismatched: list[tuple[str, str, str]] = []  # (rel, expected, actual)
        self.missing: list[str] = []     # manifest にあるが現物無し
        self.unexpected: list[str] = []  # 現物にあるが manifest に無い

    def has_critical_problem(self) -> bool:
        # mismatch / missing は重大 (差し替え or 削除されている)
        return bool(self.mismatched) or bool(self.missing)

    def summary(self) -> str:
        return (
            f"matched={len(self.matched)} mismatched={len(self.mismatched)} "
            f"missing={len(self.missing)} unexpected={len(self.unexpected)}"
        )


def verify_models(
    models_dir: Optional[Path] = None,
    manifest_path: Optional[Path] = None,
) -> ModelIntegrityResult:
    """現状の hash と manifest を比較して結果を返す。"""
    if models_dir is None:
        models_dir = DEFAULT_MODELS_DIR
    if manifest_path is None:
        manifest_path = DEFAULT_MANIFEST_PATH

    result = ModelIntegrityResult()
    expected = parse_manifest(manifest_path)
    actual = compute_manifest(models_dir)

    for rel, exp_hex in expected.items():
        if rel not in actual:
            result.missing.append(rel)
        elif actual[rel] != exp_hex:
            result.mismatched.append((rel, exp_hex, actual[rel]))
        else:
            result.matched.append(rel)

    for rel in actual:
        if rel not in expected:
            result.unexpected.append(rel)

    return result


def verify_and_log(
    *,
    fail_on_mismatch: bool = False,
    models_dir: Optional[Path] = None,
    manifest_path: Optional[Path] = None,
) -> ModelIntegrityResult:
    """起動時に呼ばれる薄いラッパ. エラー時は logger に CRITICAL + (任意で exit)."""
    result = verify_models(models_dir=models_dir, manifest_path=manifest_path)
    if result.has_critical_problem():
        for rel, exp, act in result.mismatched:
            logger.critical(
                "model integrity MISMATCH path=%s expected=%s actual=%s",
                rel, exp[:12] + "...", act[:12] + "...",
            )
        for rel in result.missing:
            logger.critical("model integrity MISSING path=%s (in manifest, not on disk)", rel)
        if fail_on_mismatch:
            import sys
            sys.stderr.write(
                f"[FATAL] model integrity check failed: {result.summary()}\n"
                "Refusing to start. Either restore the model files or regenerate "
                "SHA256SUMS via `python -m backend.scripts.regenerate_model_manifest`.\n"
            )
            sys.exit(3)
    elif result.unexpected:
        for rel in result.unexpected:
            logger.warning(
                "model integrity UNEXPECTED path=%s (on disk, not in manifest — regenerate manifest if intentional)",
                rel,
            )
        logger.info("model integrity OK with %d unexpected new files (%s)", len(result.unexpected), result.summary())
    else:
        logger.info("model integrity OK (%s)", result.summary())
    return result
